# Generated by Django 5.1 on 2024-10-23 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('factures', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facture',
            name='num',
        ),
    ]
