# Generated by Django 5.1 on 2024-10-23 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factures', '0002_remove_facture_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='facture',
            name='paid',
            field=models.BooleanField(default=False),
        ),
    ]
